spring:
  mail:
    host: smtp.exmail.qq.com
    username:
    password:
    default-encoding: UTF-8
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url:
    username:
    password:
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
mail:
  fromMail:
    addr:
server:
  port: 80
kindle:
  swagger:
    enable: true
  kv:
    secret: wanli
#  ssl:
#    #keytool -genkeypair -alias tomcat -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#    key-store: keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat